### PR TITLE
Feature/profile update

### PR DESCRIPTION
**Pull request by aramrattan**

### CODE REVIEW

**Comment by aagavin** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/kanaoreeves/keanufrombehind) found an issue: Exactly one space required after comma
        self.assertIsNotNone(result,  'No user info')
                                   ^

It's currently on:
[tests\customer_test.py:44
](https://github.com/KanaoReeves/KeanuFromBehind/blob/5937b82ade66acf6659b6325ae49bfef73b9fcae/tests/customer_test.py#L44)Commit 5937b82ade66acf6659b6325ae49bfef73b9fcae

**Comment by aagavin** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/kanaoreeves/keanufrombehind) found an issue: Trailing newlines

It's currently on:
[tests\customer_test.py:68
](https://github.com/KanaoReeves/KeanuFromBehind/blob/5937b82ade66acf6659b6325ae49bfef73b9fcae/tests/customer_test.py#L68)Commit 5937b82ade66acf6659b6325ae49bfef73b9fcae

**Comment by aagavin** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/kanaoreeves/keanufrombehind) found an issue: Unused variable 'reg_result'

It's currently on:
[tests\customer_test.py:53
](https://github.com/KanaoReeves/KeanuFromBehind/blob/5937b82ade66acf6659b6325ae49bfef73b9fcae/tests/customer_test.py#L53)Commit 5937b82ade66acf6659b6325ae49bfef73b9fcae

**Comment by aagavin** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/kanaoreeves/keanufrombehind) found an issue: Exactly one space required after comma
        result = self.app.post('/customer/profile/edit', data=updated_data,  headers={'token': json_response})
                                                                          ^

It's currently on:
[tests\customer_test.py:61
](https://github.com/KanaoReeves/KeanuFromBehind/blob/b25f9693b85f8c2a92bb3401e628abc019000913/tests/customer_test.py#L61)Commit b25f9693b85f8c2a92bb3401e628abc019000913

**Comment by aagavin** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/kanaoreeves/keanufrombehind) found an issue: Unused g imported from flask

It's currently on:
[tests\customer_test.py:3
](https://github.com/KanaoReeves/KeanuFromBehind/blob/5937b82ade66acf6659b6325ae49bfef73b9fcae/tests/customer_test.py#L3)Commit 5937b82ade66acf6659b6325ae49bfef73b9fcae

**Review by aagavin — CHANGES_REQUESTED** [review]
see code factor comments

**Comment by aramrattan** [comment]
@aagavin the code factor is ignoring my changes

**Review by aagavin — APPROVED** [review]

**Pull request merged**
